# ASSIGNMENT 1                                                McGill:COMP766-2 - Winter 2021 
Student name (ID)

In [2]:
import numpy as np
import networkx as nx
from utils import tensor_mult

### Problem 1. (5 points)

- __a__: 2 points) Derive the __Markov__ inequality below for a positive discrete random variable
(_Hint:_ rearrange to prove $a P(x \geq a) \leq \mathbb{E}[X]$ and substitute the definition of expectation.)
$$P(x > a) \leq \frac{\mathbb{E}[X]}{a}$$
- __b__: 3 points) Using this inequality prove the following, known as __Chebyshev__ inequality:
$$P(|X - \mathbb{E}[X]| > a) < \frac{Var(X)}{a^2}$$

### Solution
__a__) At first we calculate $ \mathbb{E}[X] $ :

$$\mathbb{E}[X] = \sum_x xp(x) = \sum_{x < a} xp(x) + \sum_{x \geq a} xp(x)$$

$$\Rightarrow \mathbb{E}[X] \geq \sum_{x \geq a} xp(x)dx  \geq \sum_{x \geq a} ap(x)dx = a\sum_{x \geq a} p(x)dx$$

$$\Rightarrow \mathbb{E}[X] \geq a\sum_{x \geq a} p(x)dx = a(P(x\geq a)$$

$$\Rightarrow P(x \geq a) \leq \frac{\mathbb{E}[X]}{a}$$

__b__) We can assume that $x = (X-\mathbb{E}[X])^2$ and $ a=a^2$ in from previous inequality:

We know that: $$P((X-\mathbb{E}[X])^2>a^2) = P(|X-\mathbb{E}[X]|>a)$$

Therefore:
$$P((X-\mathbb{E}[X])^2>a^2) \leq \frac{\mathbb{E}[(X-\mathbb{E}[X])^2]}{a^2}$$

$$ \Rightarrow P(|X-\mathbb{E}[X]|>a) \leq \frac{\mathbb{E}[(X-\mathbb{E}[X])^2]}{a^2}$$

$$ \Rightarrow P(|X-\mathbb{E}[X]|>a) \leq \frac{Var(X)}{a^2}$$


### Problem 2. (5 points)

In showing that factorization in a Markov Network leads to local CIs we used the
following fact. Prove it using the definition of conditional independence:

$$
P \models (X \perp Y \mid Z) \quad \Leftrightarrow \quad P(X=x, Y=y, Z=z) = f(x, z)g(y,z) 
$$


### Solution

- $\Rightarrow$) 2 points 

We know that: $$P \models (X \perp Y \mid Z) \Leftrightarrow P(X,Y|Z) = P(X|Z)P(Y|Z)$$

From chain rule we have: $$P(X,Y,Z) = P(X,Y|Z)P(Z)$$

Therefore: $$\Rightarrow P(X,Y,Z) = P(X|Z)P(Y|Z)P(Z) = P(X|Z)P(Y,Z) $$

- $\Leftarrow$) 3 points


### Problem 3. (10 points)

Here, we want to represent the joint probability $P(D,I,G,S,L)$ and answer arbitrary queries such as $P(D,I \mid G=0, L=1)$ for the running example below that we used extensively in the class.
<img src="3_4.png" width="400">
For this, we need to define CPTs. We use the ```networkx``` package to represent a DAG and add CPTs as node attributes. the CPT for a node with $K$ parents is a $K+1$ dimensional array, where the first dimension is for the child node and the order of parents follows their order when the method ```DAG.predecessors(node)``` is called. This is the order in which the corresponding edges are added. 

Your task is to write the body of the function ```Pr()``` that calculates the array of the posterior marginal, given a DAG -- e.g., $P(D, L \mid G= 2, I = 1)$. 
For your implementation you can use the ```tensor_mult``` helper function provided in ```utility.py```. 

You can try implementing this function in three steps:

- calculate the joint PMF
- condition on the evidence (e.g., by multiplying the joint array with appropriate tensor of 0s and 1s.
- marginalize and normalize the final results (normalization might be necessary depending on your implementation of conditioning on the evidence)

There are more efficient ways of calculating the posterior marginals that we study in the __inference__ lectures.

### Solution

In [145]:
# creating the BayesNet
BN = nx.DiGraph()
BN.add_node('D', cpt=np.array([.6,.4]))
BN.add_node('I', cpt=np.array([.7,.3]))

#a 3-dimensional array of shape 3x2x2 representing P(G|I,D).  
#note that the order of parents matters, here we have made sure the order is the same as
#the order returned by BN.predecessors('G')
BN.add_node('G', cpt=np.array([[[.3,.05],[.9,.5]],[[.4,.25],[.08,.3]],[[.3,.7],[.02,.2]]]))
BN.add_node('L', cpt=np.array([[.1,.4,.99],[.9,.6,.01]]))
BN.add_node('S', cpt=np.array([[.95,.2],[.05,.8]]))

# adding edges (note that the order of I,D -> G is important)
BN.add_edge('I','G')
BN.add_edge('D','G')
BN.add_edge('G', 'L')
BN.add_edge('I', 'S')

print("Is this a DAG? {}".format(nx.is_directed_acyclic_graph(BN)))
# we can use topological sort to get a topological ordering of nodes. What is the complexity of this sorting op.?
print(list(nx.topological_sort(BN)))

cpt = nx.get_node_attributes(BN, "cpt")
# print(cpt['G'][0,0])

# c1 = tensor_mult(cpt['I'], cpt['S'], [0], [1])
# print(c1[0,1])
# c2 = tensor_mult(c1, cpt['D'], [], [])
# print(c2[1,1])
# c3 = tensor_mult(c2, cpt['G'], [0,2], [1,2])
# print(c3.shape)
# P = tensor_mult(c3, cpt['L'], [3], [1])

# print(P[1,1,0,1,0])
# a=np.sum(P, axis=(1,3))/0.42   
# print(a[0,0,1])
# print(np.sum(P, axis=(1,3,4)))
# print(np.sum(P, axis=(1,2,3,4)))


def Pr(target, 
       evidence, # a dictionary of observations to conditin on -- eg, {'L':0, 'I':1}
       DAG #DAG containing the CPTs (BN above)
      ):
    
    sorted_BN = list(nx.topological_sort(BN))
    
    # creating the tensor of joint probabilities
    c1 = tensor_mult(cpt['I'], cpt['S'], [0], [1])
    c2 = tensor_mult(c1, cpt['D'], [], [])
    c3 = tensor_mult(c2, cpt['G'], [0,2], [1,2])
    P = tensor_mult(c3, cpt['L'], [3], [1])

    #Calculating the margin of non evidences
    evidence_keys = list((evidence.keys()))
    evidence_values = list((evidence.values()))
    margin_denum = P.copy()
    margin_axises = []
    margin_values = []
    ax = 0
    for i,node in enumerate(sorted_BN):
        if node not in evidence_keys:
            margin_axises.append(ax)
            margin_denum = margin_denum.sum(axis=ax)
            
        else:
            ax += 1
            margin_values.append(evidence[node]) #topological sorting evidence values
    
    
    
    #Calculating the margin of joint prbability of target and evidences
    joint_axises = []
    join_nodes = []
    margin_joint = P.copy()
    ax = 0
    for i,node in enumerate(sorted_BN):
        if node not in evidence_keys and node not in target:
            joint_axises.append(ax)
            margin_joint = margin_joint.sum(axis=ax)
            
        else:
            ax += 1
            join_nodes.append(node)

    
#     slice_axises = []
#     for i,node in enumerate(join_nodes):
#         if node in evidence_keys:
#             slice_axises.append(i)
            
#     for idx in slice_axises:
#         print(margin_joint.shape)
#         margin_joint=margin_joint.take(indices=evidence[join_nodes[i]], axis=idx)
    idx = 0  
    for i,node in enumerate(join_nodes):
        if node in evidence_keys:
            margin_joint = margin_joint.take(indices=evidence[node],axis=idx)
        else:
            idx +=1
    ax = 0  
    topologiacal_order_axis = []
    input_order = []
    target_sorted = []
    for node in sorted_BN:
        if node in target:
            target_sorted.append(node)
            input_order.append(target.index(node))
            topologiacal_order_axis.append(ax)
            ax +=1
    
    for i in topologiacal_order_axis:
        print("Axises are:", i, target.index(target_sorted[i]))
        if (topologiacal_order_axis == input_order):
            break;
        if (i != target.index(target_sorted[i])):
            margin_joint = np.swapaxes(margin_joint, i, target.index(target_sorted[i]))
            topologiacal_order_axis[i], topologiacal_order_axis[target.index(target_sorted[i])] = topologiacal_order_axis[target.index(target_sorted[i])], topologiacal_order_axis[i]
        print(margin_joint)
            
    
    marginal = margin_joint/margin_joint.sum()
    return marginal
# for Z in [{},{'I':0}, {'G':0}, {'L':0}, {'I':0,'G':0}, {'I':0,'L':0}, {'L':0,'G':0}, {'I':0,'G':0,'L':0}]:
evidence = {'S':0,'G':0}
target = ['D','I']
target2 = ['I','D']


res = Pr(target,evidence,BN)
print("P is",res.shape)
res2 = Pr(target2,evidence,BN)
print("P is",res2.shape)
print(res-res2)

Is this a DAG? True
['I', 'S', 'D', 'G', 'L']
Axises are: 0 1
[[0.1197 0.0324]
 [0.0133 0.012 ]]
Axises are: 0 1
P is (2, 2)
Axises are: 0 0
P is (2, 2)
[[ 0.          0.10766629]
 [-0.10766629  0.        ]]


### Problem 4. (10 points)

Your task in this assignment is to implement __D-separation__ algorithm for a DAG representation, similar to what we used in the previous problem. Note that (assuming non-deterministic factors) D-separation does not need access to the CPTs. The following function returns ```True``` if the given CI holds and ```False``` otherwise.

In [76]:
def is_collider(X,Y,Z,DAG):
    return (X in BN.predecessors(Z)) and (Y in BN.predecessors(Z))

def is_cond_independent(X, #non-empty list of nodes -- e.g., ['I', 'D'] 
                        Y, #non-empty list of nodes. It has no intersection with X -- e.g., ['S']
                        Z, #list of nodes -- e.g., []
                        DAG #networkx DAG -- e.g., BN defined above
                       ):
    is_CI = False
    
    #BFS traversal
    mark = list(Z)
    for z in Z:
        if len(list(BN.successors(z)))==0 and len(list(BN.predecessors(z)))==1 and list(BN.predecessors(z))[0] not in mark:
            mark = mark + list(BN.predecessors(z)) 
            print(z)
        
    visited = []
    
    for x in X: 
        for y in Y: 
            paths = list(nx.all_simple_paths(BN.to_undirected(),x,y))
            for path in paths:
                for i,v in enumerate(path):
                    if (i>0 and i<len(path)-1):
                        if(v == y):
                            is_CI = False

                        if (is_collider(path[i-1],path[i+1],v,BN) and v not in mark) or (not is_collider(path[i-1],path[i+1],v,BN) and v in mark):
                            is_CI = True
            
            
            
#     Q = []
#     Q.append(X)
#     visited.append(X)
#     while len(Q) != 0:
#         v = Q.pop(0)
#         neighbours = list(BN.successors(v))+list(BN.predecessors(v))
        
#         for w in neighbours:
#             if w not in visited:
#                 path.append('')
#                 if (w == Y):
#                     Q = []
# #                     is_CI = False
#                     break;
                
#                 if (is_collider(w,BN) and w not in mark) or (not is_collider(w,BN) and w in mark):
                    
#                     Q = []
#                     is_CI = True
#                     break;
#                 Q.append(w)
#                 visited.append(w) 
        
        return is_CI;

ci = is_cond_independent('D','I',['G'],BN)
print(ci)

False


Let us verify that the CIs that we get from D-separation, match the definition of conditional independence using the conditional probabilities that we can numerically calculate using your solution to the problem 3. 
In the following we look at all queries in the form of $P \overset{?}{\models} {D} \perp {S} \mid \mathbf{Z} = \mathbf{0}$, where $\mathbf{Z} \subseteq \{I,G,L\}$ may contain any of the remaining variables. 

In [151]:
domains = {'I':[0,1], 'L':[0,1], 'G':[0,1,2]}
for Z in [{},{'I':0}, {'G':0}, {'L':0}, {'I':0,'G':0}, {'I':0,'L':0}, {'L':0,'G':0}, {'I':0,'G':0,'L':0}]:
    #conditional independence from D-separation
    CI_alg = is_cond_independent(['D'], ['S'], Z.keys(), BN)
    #conditional independence according to conditional probabilities
    CI_num = np.max(np.abs(Pr(['D','S'], Z, BN) - np.outer(Pr(['D'], Z, BN),Pr(['S'], Z, BN)))) < 1e-10
    #they should match
    assert(CI_num == CI_alg)
print("passed the minimal test")


Axises are: 0 1
[[0.435 0.165]
 [0.29  0.11 ]]
Axises are: 0 1
Axises are: 0 0
Axises are: 0 0
Axises are: 0 1
[[0.399 0.021]
 [0.266 0.014]]
Axises are: 0 1
Axises are: 0 0
Axises are: 0 0
Axises are: 0 1
[[0.1521 0.1359]
 [0.0253 0.0487]]
Axises are: 0 1
Axises are: 0 0
Axises are: 0 0
L
Axises are: 0 1
[[0.1994178 0.0306462]
 [0.2211    0.0465   ]]
Axises are: 0 1
Axises are: 0 0
Axises are: 0 0
Axises are: 0 1
[[0.1197 0.0063]
 [0.0133 0.0007]]
Axises are: 0 1
Axises are: 0 0
Axises are: 0 0
L
Axises are: 0 1
[[0.194313 0.010227]
 [0.212268 0.011172]]
Axises are: 0 1
Axises are: 0 0
Axises are: 0 0
Axises are: 0 1
[[0.01521 0.01359]
 [0.00253 0.00487]]
Axises are: 0 1
Axises are: 0 0
Axises are: 0 0
Axises are: 0 1
[[1.197e-02 6.300e-04]
 [1.330e-03 7.000e-05]]
Axises are: 0 1
Axises are: 0 0
Axises are: 0 0
passed the minimal test
